# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb707a83bf142e83b8beaeb2603d1ead1ccda10dfa09ce300a8d2984e3ace74ef56ef06773d82c5056210a01fc6c8b3ba619b6e9df361c33e2cde3271b287819
  pagarme_api_key: ak_test_KoihUGGY1ZJuFhXcXZVDYSzo5CkU6n
  site_recipient: re_ciqokk0ee00mzx26efv6t0e3h

test:
  secret_key_base: d0ee311da015baa9893d40f06d826f40860ed394d5ca750dbdd3f075ad205303d5c9d57efea870f9115cde64f61d7cd7eef7de1fcca471778634eddad35794a1
  pagarme_api_key: ak_test_KoihUGGY1ZJuFhXcXZVDYSzo5CkU6n
  site_recipient: re_ciqokk0ee00mzx26efv6t0e3h

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  pagarme_api_key: <%= ENV["PAGARME_API_KEY"] %>
